---
# task file to configure exploitdb from source

- name: exploitdb | clone repository 
  become: true
  git:
    repo: https://github.com/offensive-security/exploitdb.git
    dest: /opt/exploitdb

- name: exploitdb | create symbolic link to searchsploit
  become: true
  file:
    src: /opt/exploitdb/searchsploit
    dest: /usr/local/bin/searchsploit
    state: link
