# task file installing and configuring network security packages

- name: add network security packages from apt                
  become: true
  ignore_errors: true                                                                                                                       
  apt:
    update_cache: yes
    pkg:
      - onesixtyone
      - dnsrecon
      - hunt
      - proxychains
      - hydra

- name: add network security packages from pip
  become: false
  pip:
    name:
      - crackmapexec
      - impacket
