---
# task file to install recon and osint security packages

- name: install recon and osint packages via apt
  become: true
  ignore_errors: true
  apt:
    update_cache: yes
    pkg:
      - recon-ng
