---
# task file to install web tools

- name: add web security packages from apt
  become: true
  ignore_errors: true
  apt:
    update_cache: yes
    pkg:
      - cewl
      - nikto
      - wapiti
      - recon-ng

- name: add web security packages from pip
  become: false
  pip:
    name:
      - dirhunt
