---
# tasks file to ensure flathub repository is available

- name: enable flathub repository
  become: false
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
