---
# tasks file installing and configuring social applications

- name: social | install applications via flatpak
  become: false
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop:
    - com.discordapp.Discord
    - com.mattermost.Desktop
    - com.slack.Slack
    - org.signal.Signal
    - us.zoom.Zoom
