---
# task file to manage custom configurations

- name: configs | clone dotfiles repository
  become: false
  git:
    repo: https://github.com/trevorbryant/dotfiles.git
    dest: "/home/{{ user }}/Documents/dotfiles"

- name: configs | symlink tmux config
  become: false
  file:
    src: "/home/{{ user }}/Documents/dotfiles/.tmux.conf"
    dest: "/home/{{ user }}/.tmux.conf"
    state: link

- name: configs | prepare nvim directory
  become: false
  file:
    path: "/home/{{ user }}/.config/nvim"
    state: directory

- name: configs | symlink neovim config
  become: false
  file:
    src: "/home/{{ user }}/Documents/dotfiles/.config/nvim/init.vim"
    dest: "/home/{{ user }}/.config/nvim/init.vim"
    state: link

- name: configs | load dconf
  become: false
  shell: "/usr/bin/dconf load / < /home/{{ user }}/Documents/dotfiles/dconf/dconf_all"


- name: configs | prepare autostart directory
  become: false
  file:
    path: "/home/{{ user }}/.config/autostart"
    state: directory

- name: configs | symlink autostart
  become: false
  file:
    src: "/home/{{ user }}/Documents/dotfiles/.config/autostart/org.gnome.Terminal.desktop"
    dest: "/home/{{ user }}/.config/autostart/org.gnome.Terminal.desktop"
    state: link
