---
# task file to configure neovim in place of vim

- name: neovim | remove vim packages via apt
  become: true
  ignore_errors: true
  apt:
    name: vim
    state: absent

- name: neovim | install neovim package via apt
  become: true
  apt:
    name: neovim
    state: latest

- name: neomvim | create symbolic link for nvim
  become: true
  file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    owner: root
    group: root
    mode: a+x
