---
# task file installing and configuring utility packages

- name: install utility packages via apt
  become: true
  ignore_errors: true
  apt:
    update_cache: yes
    pkg: 
      - gnome-tweaks
      - unattended-upgrades
      - snapd
      - flatpak
      - flatpak-builder
      - locate
      - curl
      - git
      - jq
      - libvpx6
      - tmux
      - neovim
      - tree
      - golang-go
      - python3
      - python3-pip
      - mupdf-tools
      - p7zip-full
      - upx-ucl
      - rar
      - pst-utils
      - dmg2img
      - php
      - sqlite3
      - awscli
      - ruby-bundler
      - ruby-dev
      - obs-studio
      - audacity
      - virt-manager
      - neofetch
      - xclip
      - knockd
      - redis-tools
      - kpcli
      - dos2unix
      - apt-transport-https
      - ca-certificates
      - gnupg
      - build-essential
